### Write a test which i can run this is too time consuming

### Get Base Path
GET localhost:3000/api/admin
Cookie: token=s%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTcwODYyMjksImRhdGEiOnsibmFtZSI6ImFkbWluIiwiZW1haWwiOiJyZXRyaWV2ZWZyb21EQiIsInJvbGUiOiJBRE1JTiJ9LCJpYXQiOjE3NTcwODI3NTF9.hvYeAL_JrYB3rre9mDpT-a7vKENJdL1-5kcgxgMexEg.%2FftlVme5dboiso4uik78sXBPfiUe9Rc8NKszSztBNiM

### Create new store
POST localhost:3000/api/admin/stores
Content-Type: application/json

{
  "name": "Test Store",
  "address": "Test Address"
}

### Create normal user
POST localhost:3000/api/admin/users
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "password123",
  "address": "SomeLane SomePlace"
}

### Create admin user
POST localhost:3000/api/admin/admin-users
Content-Type: application/json

{
  "username": "adminuser",
  "email": "admin@example.com",
  "password": "adminpass123"
}
