### Post Login Path Admin
POST localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "P@1234567"
}

### Post Login Path StoreOwner
POST localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password"
}

### Post Login Path User
POST localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "user9@example.com",
  "password": "P@1234567"
}


### Post Login Path Incorrect Creds
POST localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "password1"
}

### Post Register Path
POST localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@example.com",
  "password": "P@1234567",
  "address": "adminplace adminlane"
}

### Post Register Path
POST localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name": "    user",
  "email": "user2@example.com",
  "password": "P@1234567",
  "address": "userplace userlane"
}


### Post Register Path
POST localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "name": "storeOwner",
  "email": "storeOwner@example.com",
  "password": "P@1234567",
  "address": "storeownerplace storeOwnerlane"
}

### Post LogOut Path
POST localhost:3000/api/v1/auth/logout