### Create a new rating
POST http://localhost:3000/api/v1/rating
Content-Type: application/json

{
  "storeId": 10,
  "rating": 5
}

### Get all ratings
GET http://localhost:3000/api/v1/rating

### Get rating by ID
GET http://localhost:3000/api/v1/rating/1

### Update rating
PUT http://localhost:3000/api/v1/rating/1
Content-Type: application/json
Cookie: s%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTczMzE3MTMsImRhdGEiOnsiaWQiOjExLCJlbWFpbCI6InRlc3Q0QGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIifSwiaWF0IjoxNzU3MzE3NTYyfQ.oj-ohAGVsfJDvlFaKLMugZabXW30BmtHUrT7oEI_1tc.1s1PG3kj3%2B%2BM%2FWgKHlN2A9MlSVV1fcuEZ0%2BJWnmN22s

{
  "id": 2,
  "rating": 4
}

### Delete rating
DELETE http://localhost:3000/api/v1/rating/1