### Create new store
POST http://localhost:3000/api/v1/store
Content-Type: application/json

{
  "name": "testStore",
  "email": "testStore1@store.com",
  "address": "TestLaneForTestStore",
  "ownerId": 12
}

### Get all stores
GET http://localhost:3000/api/v1/store