### Create a new user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "test",
  "email": "test6@example.com",
  "password": "password",
  "address": "someplace somelane"
}


### Get all users
GET http://localhost:3000/api/v1/users

### Get user by ID
GET http://localhost:3000/api/v1/users/1

### Update user
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json
Cookie: token=s%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTcyMjE1NDUsImRhdGEiOnsiaWQiOjExLCJlbWFpbCI6InRlc3Q0QGV4YW1wbGUuY29tIiwicm9sZSI6IlVTRVIifSwiaWF0IjoxNzU3MjE4MDY3fQ.bG9nfUvbZ8rNv5pvhOo8okDiGr6JX7wMqdpE4GuoWAc.eeBOcz57MEX6nJGM2Ab4hPKgFF2Ei%2B63tShJMTraoP4

{
  "password": "newpassword"
}

### Delete user
DELETE http://localhost:3000/api/v1/users/1
